Use {{.tuberAppName}} in YAMLs in init command
Freshly/tuber pull request #142
Opened 2020-09-17 06:28 UTC by Hbbb

2020-09-17 15:10 UTC, jkminneti commented on pkg/core/init.go
> +	templateData := map[string]string{}
what's this stuff about? seems like this wouldnt work

2020-09-24 23:47 UTC, jkminneti requested changes
`go generate ./...`
`data\tuberapps\gen.go` for context

2020-09-25 16:06 UTC, quinn-freshly approved these changes

2020-09-29 18:10 UTC, Hbbb commented on pkg/core/init.go
> +	templateData := map[string]string{}
It's because the underlying function takes in a `map[string]string` and I didn't want to change it to handle nil. This works.

2020-10-01 17:34 UTC, jkminneti approved these changes

2020-10-01 17:34 UTC, merged