Add portforwarding command
Freshly/tuber pull request #149
Opened 2020-10-02 20:59 UTC by Jefferson-Faseler

Adds `port-forward` command. Can be used with all features of the `kubectl` command of the same name.
`tuber port-forward -a user-service 8989`
To open a port on localhost:8989 -> pod::8989

Ports can are a variadic list that also take advantage of the `:` syntax in the `kubectl port-forward` [command](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#port-forward). 

`tuber port-forward -a user-service -p user-service-8822272-fsdalhj 9001` to specify a particular pod.

Able to specify the workload, local IP addresses, and pod wait time in addition to the small examples above.

Also, as an added bonus I gave `exec` the ability to specify a pod as well. Specifying a pod has many added benefits, like faster command times and edge-cases for a-typically configured pods.

2020-10-03 00:01 UTC, jaysonesmith reviewed
Not sure my reviews are necessarily going to be super useful right now, but I've asked some questions to try to get a better understanding and stuff.

2020-10-03 00:01 UTC, jaysonesmith commented on cmd/helpers.go
> +var workload string
Oh wait, are these being set by Cobra?

2020-10-05 16:06 UTC, Jefferson-Faseler commented on cmd/helpers.go
> +var workload string
Yes, they are set by Cobra in commands that share the need for these vars; `exec`, and `port-forward`.

2020-10-05 18:58 UTC, Jefferson-Faseler commented on cmd/portForward.go
> +	portForwardCmd.Flags().StringVar(&address, "address", "localhost", "specify an address on your local machine to forward from. Can be a comma separated list. Only IP addresses and 'localhost' are val
Yeah, let k8s do the work for parsing it. No need to reinvent the wheel here IMO.

2020-10-05 19:06 UTC, Jefferson-Faseler commented on cmd/exec.go
> +	podName, err := fetchPodname()
Oh gosh. 🤦 Nice catch

2020-10-05 19:11 UTC, Jefferson-Faseler commented on cmd/exec.go
> +		containerName = fetchWorkload()
It is also used in https://github.com/Freshly/tuber/blob/add-portforwarding-command/cmd/helpers.go#L196 for fetching pod names.

2020-10-08 21:05 UTC, jkminneti requested changes
using the simplest example, 
```
tuber exec -a user-service -w user-service-sidekiq
```
it returns 
```
error: you must specify at least one command for the container
```
upon the kubectl exec.

debug logs indicate the pod name was successfully identified.

2020-10-08 21:07 UTC, Jefferson-Faseler commented
> using the simplest example,
> 
> ```
> tuber exec -a user-service -w user-service-sidekiq
> ```
> 
> it returns
> 
> ```
> error: you must specify at least one command for the container
> ```
> 
> upon the kubectl exec.
> 
> debug logs indicate the pod name was successfully identified.

I'm confused. Are you suggesting I make changes to the `exec` command? I think the output would describe why you are seeing the error.

2020-10-08 21:10 UTC, jkminneti commented on cmd/portForward.go
> +tuber exec -a user-service -w user-service-sidekiq
not exec

2020-10-08 21:11 UTC, Jefferson-Faseler commented on cmd/portForward.go
> +tuber exec -a user-service -w user-service-sidekiq
Oh hey, good catch

2020-10-08 21:11 UTC, jkminneti commented on cmd/portForward.go
> +tuber exec -a user-service -w user-service-sidekiq
i had copy pasted from that line in the docs (to explain my previous comment lol)

2020-10-08 21:15 UTC, jkminneti commented on cmd/portForward.go
> +	Args:         cobra.MinimumNArgs(1),
exactargs?

2020-10-08 21:19 UTC, Jefferson-Faseler commented on cmd/portForward.go
> +	Args:         cobra.MinimumNArgs(1),
Nope, as many as your ❤️ desires

2020-10-08 21:20 UTC, Jefferson-Faseler commented on cmd/portForward.go
> +	Args:         cobra.MinimumNArgs(1),
Well, technically 65535 args max

2020-10-08 21:21 UTC, jkminneti commented on cmd/portForward.go
> +	Args:         cobra.MinimumNArgs(1),
why though? not like it's variadic

2020-10-08 21:22 UTC, Jefferson-Faseler commented on cmd/portForward.go
> +	Args:         cobra.MinimumNArgs(1),
It is https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#port-forward

2020-10-08 21:24 UTC, jkminneti commented on cmd/portForward.go
> +	Args:         cobra.MinimumNArgs(1),
`one or more local ports to a pod` why would anyone... but whatever you're absolutely right

2020-10-15 17:02 UTC, jkminneti commented on cmd/portForward.go
> +	Use:          "port-forward -a appName [port(s)]",
ok call it pedantic, but i don't like the `-a`. could easily do `tuber port-forward payment-service 8080`

in fact, what if we assumed 8080 by default

2020-10-15 17:02 UTC, jkminneti commented on cmd/portForward.go
> +	return err
this should at least print a clickable link. bonus brownie taco pizza points if it were to open your default web browser to it

2020-10-15 18:28 UTC, Jefferson-Faseler commented on cmd/portForward.go
> +	return err
I don't think I'm going to do this change. A brownie taco pizza sounds very unpleasant.

2020-10-15 18:34 UTC, Jefferson-Faseler commented on cmd/portForward.go
> +	Use:          "port-forward -a appName [port(s)]",
I'm matching what exec's syntax is so ditching `-a` would change that command as well. 

Supplying port(s) is not difficult for a user to do. I would think it is better to have tuber complain someone did not pass a port so they know it's a thing.

2020-10-15 18:38 UTC, jkminneti commented on cmd/portForward.go
> +	return err
not even the clickable link though?

2020-10-15 18:40 UTC, jkminneti commented on cmd/portForward.go
> +	Use:          "port-forward -a appName [port(s)]",
for us it makes sense, is intuitive, and is easy. but for someone who doesnt understand what port-forwarding is, some sensible defaults could get them into their sidekiq-web. 

i'm imagining "which port do i need for sidekiq" kinds of questions

2020-10-15 18:40 UTC, Jefferson-Faseler commented on cmd/portForward.go
> +	return err
I can look into it 😒

2020-10-15 18:42 UTC, Jefferson-Faseler commented on cmd/portForward.go
> +	Use:          "port-forward -a appName [port(s)]",
For sidekiq, sure. What about postgres, redis, memcached, applications (tls and http)? Then the portforwarding doesn't work by default and we have the same question

2020-10-15 18:44 UTC, jkminneti commented on cmd/portForward.go
> +	Use:          "port-forward -a appName [port(s)]",
that's the thing, though - this isn't supposed to be a `kubectl` wrapper, it's supposed to be a "service mesh tool for app devs"

2020-10-19 18:31 UTC, jkminneti approved these changes

2020-10-19 18:33 UTC, merged