Add Local Testing Guide
Freshly/tuber pull request #160
Opened 2020-11-10 20:09 UTC by Hbbb

2020-11-10 20:20 UTC, jkminneti requested changes

2020-11-10 20:20 UTC, jkminneti commented on doc/testing/testing_locally.md
> +There are several ways to trigger events that will cause tuber to re-build your app. The potatoes cloud build trigger is configured to build on pushes to any branch, so it's ideal for testing.
this is OSS - no potatoes, no links to our gcp resources, etc.

2020-11-10 20:22 UTC, jkminneti commented on doc/testing/testing_locally.md
> +There are several ways to trigger events that will cause tuber to re-build your app. The potatoes cloud build trigger is configured to build on pushes to any branch, so it's ideal for testing.
if we want functional prebuilt stuff in the docs, we need a dedicated private repo for tuber stuff (which may be ideal anyway for tuber configs)

2020-11-10 21:59 UTC, Hbbb commented on doc/testing/testing_locally.md
> +There are several ways to trigger events that will cause tuber to re-build your app. The potatoes cloud build trigger is configured to build on pushes to any branch, so it's ideal for testing.
Maybe this makes more sense as a handbook entry? I my focus is not on a generic testing guide, it's more about enabling developers at Freshly to be able to work with tuber.

2020-11-12 16:41 UTC, Hbbb commented
I've moved this guide to the handbook.

2020-11-12 16:41 UTC, closed without merging