admin dash - gin
Freshly/tuber pull request #178
Opened 2021-04-12 17:30 UTC by jkminneti

sorry quinn

2021-04-17 05:39 UTC, jaysonesmith commented on pkg/adminserver/reviewapp.go
> +	var status = http.StatusOK
Can we normalize var creation here?

2021-04-17 05:46 UTC, jaysonesmith commented on pkg/adminserver/reviewapp.go
> +	var status = http.StatusOK
It's actually -only- being used on the very last line of this method and every other call to `c.HTML` uses the http type helper directly in the call. Can we actually get rid of this and normalize to the rest of the calls?

2021-04-17 06:17 UTC, jaysonesmith commented on pkg/adminserver/reviewapp.go
> +	data.NoSuccessfulBuild = !successfulBuildExists
It'd probably be easier to follow some of this by changing the field to successfulBuild setting it to true when a success is found. The template will need to have the if swapped also. As it's written right now, there's a bit of double negative mental gymnastics to follow. 

Additionally, the update would allow us to use the zero value as a meaningful default.

2021-04-17 06:25 UTC, jaysonesmith commented on pkg/adminserver/reviewapp.go
> +	data.Builds = builds
I prefer this up on 56 closer to where it's defined for readability. After that, if you wanted the for loop could also be changed to iterate over `data.Builds` instead. 🤷

2021-04-17 06:30 UTC, jaysonesmith commented on pkg/adminserver/reviewapp.go
> +	config, err := k8s.GetConfigResource(reviewapps.TuberReviewTriggersConfig, "tuber", "configmap")
Unchecked error.

2021-04-17 06:36 UTC, jaysonesmith commented on pkg/adminserver/app.go
> +	var status = http.StatusOK
Same thing here about the single use variable and mismatched indirect/direct usage

2021-04-17 06:41 UTC, jaysonesmith commented on pkg/adminserver/createreviewapp.go
> +	appName := c.Param("appName")
These are both only used once

2021-04-17 06:44 UTC, jaysonesmith commented on pkg/adminserver/dashboard.go
> +	data := dashboardResponse{Title: "potate"}
Ooooh, I assume this is where the status stuff I commented on earlier originated here?

2021-04-17 06:48 UTC, jaysonesmith commented on pkg/adminserver/deletereviewapp.go
> +		c.Redirect(http.StatusFound, "/tuber/apps/"+sourceAppName+"?error="+errString)
Concatenationception! 😅

2021-04-17 06:54 UTC, jaysonesmith commented on pkg/adminserver/deletereviewapp.go
> +		c.Redirect(http.StatusFound, "/tuber/apps/"+sourceAppName+"?error="+errString)
During your testing did you ever find that the value for errString got out of hand or anything with stuff bubbling up?

2021-04-17 06:55 UTC, jaysonesmith commented on pkg/adminserver/reviewapp.go
> +	sourceAppName := c.Param("appName")
This var is only used once on line 38. Do you feel it would be cleaner to just call `c.Param` directly on 38 instead of creating a single use variable?

2021-04-17 07:20 UTC, jaysonesmith commented on pkg/adminserver/templates/reviewApp.html
> +      {{end}}</table>
Not sure if the placement of the table elements this was for output whitespace, but you can do this too (iirc):

```
<table>
      {{- range $build := .Builds -}}
            <tr>
                  <td><a href="{{$build.Link}}">{{$build.StartTime}}</a></td>
                  <td>{{$build.Status}}</td>
            </tr>
      {{end -}}
</table>
  ```

The space hyphen indicates to trim whitespace from between the template element and the html elemet.

2021-04-17 07:22 UTC, jaysonesmith approved these changes

2021-04-19 16:31 UTC, Hbbb requested changes
A few small things

2021-04-19 16:31 UTC, Hbbb commented on pkg/adminserver/server.go
> +	ctx                 context.Context
This is an anti-pattern according to the official Go documentation. https://blog.golang.org/context-and-structs.

Context is explicitly defined as a request-scoped argument that should be passed in to each handler.

2021-04-19 16:31 UTC, Hbbb commented on pkg/adminserver/server.go
> +func (s server) start() error {
Why not use a pointer receiver here? I realize you're not modifying anyting on `server`, but it is a fairly large struct to be copying all the time. This applies to all of the methods on server.

2021-04-19 16:31 UTC, Hbbb commented on pkg/adminserver/deletereviewapp.go
> +	err := reviewapps.DeleteReviewApp(s.ctx, reviewAppName, s.creds, s.triggersProjectName)
Expanding on my other comment about storing context on `server`, shouldn't you be passing the `c *gin.Context` around? Or using the underlying context `c.Request.Context()` and passing that around? I'm fairly certain we shouldn't be storing context on a struct.

2021-04-19 16:31 UTC, Hbbb commented on pkg/adminserver/dashboard.go
> +	data := dashboardResponse{Title: "potate"}
Were you meaning to change the title here?

2021-04-19 16:31 UTC, Hbbb commented on pkg/adminserver/dashboard.go
> +	if err != nil {
I think it makes sense to wrap this error with a more context-appropriate message. Right now, if `core.TuberSourceApps()` fails, the error message it will return will come all the way from `os.Exec`.

2021-04-19 16:31 UTC, Hbbb commented on pkg/adminserver/createreviewapp.go
> +	reviewAppName, err := reviewapps.CreateReviewApp(s.ctx, s.logger, branch, appName, s.creds, s.triggersProjectName)
Maybe I should just leave this as the final comment of the review because I think it applies to a lot of the `reviewapps` functions. I think it makes sense to wrap errors inside `reviewapps.CreateReviewApp` with a more contextually relevant string. I don't think it makes sense to render `kubectl` errors to the UI.

2021-04-19 16:31 UTC, Hbbb commented on pkg/adminserver/reviewapp.go
> +	if err != nil {
Maybe wrap this error? Cloud Build service errors seem like they'd be scary and hard to decipher.

2021-04-19 16:31 UTC, Hbbb commented on pkg/adminserver/reviewapp.go
> +			parsed, timeErr := time.Parse(time.RFC3339, build.StartTime)
If there's an error parsing `build.StartTime`, won't `parsed` be nil?

2021-04-23 02:56 UTC, jkminneti commented on pkg/adminserver/createreviewapp.go
> +	appName := c.Param("appName")
i sorta liked how all of the stuff we're pulling from the request is at the top, but, looking at it now, i dont mind the alternative

2021-04-23 02:57 UTC, jkminneti commented on pkg/adminserver/dashboard.go
> +	data := dashboardResponse{Title: "potate"}
> Were you meaning to change the title here?

potate

2021-04-23 03:00 UTC, jkminneti commented on pkg/adminserver/deletereviewapp.go
> +		c.Redirect(http.StatusFound, "/tuber/apps/"+sourceAppName+"?error="+errString)
thought was while this feature is in infancy, it'd make things easier to debug. given we're jumping right into client usage here, wrapping all de errors and logging instead

2021-04-23 03:03 UTC, jkminneti commented on pkg/adminserver/templates/reviewApp.html
> +      {{end}}</table>
havent really landed on how i like to see go templated html and goland does weird stuff with it anyway.

going with this for now because i definitely wasnt trying to do anything with whitespace:
```go
	<table>
			{{range $build := .Builds}}
			<tr>
				<td><a href="{{$build.Link}}">{{$build.StartTime}}</a></td>
				<td>{{$build.Status}}</td>
			</tr>
      {{end}}
	</table>
```

2021-04-23 03:04 UTC, jkminneti commented on cmd/adminserver.go
> +	err = adminserver.Start(ctx, logger, triggersProjectName, creds, viper.GetBool("reviewapps-enabled"), viper.GetString("cluster-default-host"))
it's not necessary for startup

2021-04-23 03:06 UTC, jkminneti commented on pkg/reviewapps/triggers.go
> +const TuberReviewTriggersConfig = "tuber-review-triggers"
they're used in this pr:
```
func reviewAppBuilds(reviewAppName string, triggersProjectName string, cloudbuildClient *cloudbuild.Service) ([]Build, error) {
	config, err := k8s.GetConfigResource(reviewapps.TuberReviewTriggersConfig, "tuber", "configmap")
```

2021-04-23 03:09 UTC, jkminneti commented on pkg/adminserver/server.go
> +func (s server) start() error {
_does_ it get copied?

like if we tell gin to use 
```
tuber.GET("/", s.dashboard)
```
does passing that function imply a new copy is made every time that function is run?

2021-04-23 03:25 UTC, jkminneti commented on pkg/adminserver/createreviewapp.go
> +	reviewAppName, err := reviewapps.CreateReviewApp(s.ctx, s.logger, branch, appName, s.creds, s.triggersProjectName)
posting this here too

thought was while this feature is in infancy, it'd make things easier to debug. given we're jumping right into client usage here, wrapping all de errors and logging instead

2021-04-23 03:29 UTC, jkminneti commented on pkg/adminserver/reviewapp.go
> +			parsed, timeErr := time.Parse(time.RFC3339, build.StartTime)
nope, just `Time{}` (so `January 1, year 1, 00:00:00.000000000 UTC`)

2021-04-27 17:35 UTC, jaysonesmith commented on pkg/adminserver/createreviewapp.go
> +		clientError := "review app creation failed"
c6 - Did you mean to declare this to be used by both line 15 and 17?

2021-04-27 17:36 UTC, jaysonesmith approved these changes

2021-04-27 17:50 UTC, jaysonesmith commented on pkg/adminserver/server.go
> +func (s server) start() error {
https://tour.golang.org/methods/8

2021-04-27 17:50 UTC, Hbbb commented on cmd/adminserver.go
> +	err = adminserver.Start(ctx, logger, triggersProjectName, creds, viper.GetBool("reviewapps-enabled"), viper.GetString("cluster-default-host"))
Fair enough!

2021-04-27 17:51 UTC, Hbbb commented on pkg/reviewapps/triggers.go
> +const TuberReviewTriggersConfig = "tuber-review-triggers"
👍

2021-04-27 17:57 UTC, Hbbb commented on pkg/adminserver/server.go
> +func (s server) start() error {
Yea it gets copied on each invocation. I don't know that this is a _huge_ issue, it's more of a best practices thing.

2021-04-27 17:58 UTC, Hbbb commented on pkg/adminserver/reviewapp.go
> +			parsed, timeErr := time.Parse(time.RFC3339, build.StartTime)
Alright, no big deal.

2021-04-27 17:58 UTC, Hbbb approved these changes

2021-04-30 00:48 UTC, merged