POPS-1111 Remove Env Dependency
Freshly/tuber pull request #204
Opened 2021-06-10 01:55 UTC by Hbbb

* Removes dependency on env vars in CLI
* Refactors tuber config into `config` package

2021-06-10 13:38 UTC, quinn-freshly approved these changes

2021-06-12 17:43 UTC, jkminneti commented on pkg/config/main.go
> +package config
can we rename this file `config.go` for my sanity?

2021-06-14 03:32 UTC, jkminneti commented on cmd/config.go
> +	RunE:         writeConfig,
it's more like `openConfig` but obviously pedantic c6 or whatever

2021-06-14 03:53 UTC, quinn-freshly requested changes
seems to have build errors

2021-06-14 16:55 UTC, Hbbb commented on pkg/config/main.go
> +package config
Absolutely.

2021-06-14 23:52 UTC, merged