POPS-1113 Move excludedResources to TuberApp model
Freshly/tuber pull request #205
Opened 2021-06-10 18:43 UTC by Hbbb

This just updates the data model. Excluded resources aren't currently considered when creating a review app

2021-06-13 16:17 UTC, jkminneti commented on pkg/reviewapps/reviewapps.go
> +		ExcludedResources: sourceApp.ReviewAppsConfig.ExcludedResources,
```suggestion
		ExcludedResources: sourceApp.ExcludedResources,
```

2021-06-13 16:19 UTC, jkminneti commented on graph/schema.resolvers.go
> +	panic(fmt.Errorf("not implemented"))
gen problem or just actually unimplemented?

2021-06-13 16:39 UTC, jkminneti commented on pkg/reviewapps/reviewapps.go
> +		ExcludedResources: sourceApp.ReviewAppsConfig.ExcludedResources,
or also just fixed it in https://github.com/Freshly/tuber/pull/208

2021-06-14 03:25 UTC, quinn-freshly requested changes
as per convo on friday can you change this to be on the app not the review app config

2021-06-14 03:42 UTC, jkminneti commented
> as per convo on friday can you change this to be on the app not the review app config

he did tho

2021-06-14 17:06 UTC, Hbbb commented on graph/schema.resolvers.go
> +	panic(fmt.Errorf("not implemented"))
It always gens as unimplemented like this. I haven't implemented it yet. I think I tagged you a bit too early, sorry.

2021-06-15 05:13 UTC, jkminneti commented on pkg/core/releaser_test.go
> +			if got := r.exclude(tt.args.res); !reflect.DeepEqual(got, tt.want) {
ooooops

2021-06-15 05:16 UTC, jkminneti commented on pkg/core/releaser_test.go
> +			if got := r.exclude(tt.args.res); !reflect.DeepEqual(got, tt.want) {
uhhhh not sure what to do here lol i deleted the only thing that test was testing

2021-06-15 05:28 UTC, jkminneti commented on pkg/core/releaser_test.go
> +			if got := r.exclude(tt.args.res); !reflect.DeepEqual(got, tt.want) {
we can revert if you want. i haven't only cus i kinda like my solution (where the _moment_ we have a kind and name, they get chucked)

2021-06-15 15:53 UTC, quinn-freshly approved these changes

2021-06-15 16:39 UTC, merged