move frontend to separate deployment
Freshly/tuber pull request #209
Opened 2021-06-13 18:21 UTC by quinn-freshly

2021-06-13 19:54 UTC, jkminneti requested changes

2021-06-13 19:54 UTC, jkminneti commented on .tuber/virtualservice.yaml
> +            host: tuber-frontend.tuber-frontend.svc.cluster.local
new virtualservice inside of tuber-frontend should handle this

with `{{.tuberAppName}}`'s all the way down

question then becomes how to istio it. can we exact match on `/tuber/graphql` in tuber-frontend, and prefix match on `/tuber`, and have it just work?

or will we have to exact match on `/tuber`, and prefix match on `/tuber/apps` etc

either way should be doable

why? FRONTEND REVIEW APPS 🎉

2021-06-13 19:54 UTC, jkminneti commented on cloudbuild.yaml
> +steps:
should split into two cloudbuild yamls, one for frontend one for backend, _both using kaniko..._, and with file filters to match (assuming, hopefully safely, we can segment frontend by a toplevel dir)

2021-06-13 19:54 UTC, jkminneti commented on pkg/adminserver/web/.tuber/deployment.yaml
> +  name: tuber-frontend
if we do go the frontend review apps route, this should all be `{{.tuberAppName}}`'d (same for the service)

2021-06-13 19:54 UTC, jkminneti commented on pkg/iap/auth.go
> -	spew.Dump(refreshTokenFile)
🙏 🙏 🙏 🔪

2021-06-13 19:54 UTC, jkminneti commented on .tuber/persistentvolumeclaim.yaml
> -  namespace: tuber
these were there to _explicitly disallow review apps of tuber_

tuber now has a `TuberApp.ReviewAppsConfig.Enabled = false` but stilllllll idk up to you.

2021-06-13 20:24 UTC, jkminneti commented on .tuber/virtualservice.yaml
> +            host: tuber-frontend.tuber-frontend.svc.cluster.local
actually you probably use relative routing to get to `/tuber/graphql`

so if a review app is running on `/tuber-pops-123`, we'll need another route to define `/tuber-pops-123/graphql`

which means `tuber` doesn't even need a virtualservice!

2021-06-13 22:35 UTC, quinn-freshly commented on cloudbuild.yaml
> +steps:
idk how 2 kaniko

2021-06-13 22:42 UTC, quinn-freshly commented on .tuber/persistentvolumeclaim.yaml
> -  namespace: tuber
ehh, lets just use the setting now that we have it.

2021-06-14 02:33 UTC, jkminneti approved these changes
fixes the route

2021-06-14 03:11 UTC, merged