deploy endpoint 🔥
Freshly/tuber pull request #213
Opened 2021-06-14 04:59 UTC by jkminneti

🔥 🚒 🧯

2021-06-14 20:25 UTC, jaysonesmith requested changes
Great work! Just a couple checks needed.

2021-06-14 20:25 UTC, jaysonesmith commented on cmd/rollback.go
> +	appName := args[0]
Same C2 feedback as with `deploy`.

2021-06-14 21:32 UTC, jkminneti commented on graph/schema.resolvers.go
> +func (r *mutationResolver) Deploy(ctx context.Context, input model.DeployInput) (*model.TuberApp, error) {
autogenerated :(

2021-06-14 21:34 UTC, jkminneti commented on cmd/deploy.go
> +	PreRunE:       promptCurrentContext,
```go
Args: cobra.ExactArgs(1),
```
but will do good catch

2021-06-14 22:45 UTC, jaysonesmith commented on cmd/deploy.go
> +	PreRunE:       promptCurrentContext,
The issue with `ExactArgs` is that when you've got `SilenceUsage: true` set, all you get is, "2021/06/14 15:44:15 accepts 1 arg(s), received 0" which is super unhelpful.

2021-06-14 23:57 UTC, jkminneti commented on cmd/deploy.go
> +	Use:           "deploy [app] -t [tag]",
wow we have done that wrong literally everywhere. good good call

2021-06-15 00:02 UTC, jkminneti commented on cmd/deploy.go
> +	PreRunE:       promptCurrentContext,
ugh that's frustrating. but i'd question if `"app name is required"` is sufficient either

that could be a flag or something who knows

so i _want_ cobra to only display usage whenever Args errors, but it doesnt :/

2021-06-15 00:02 UTC, jkminneti commented on cmd/deploy.go
> +	PreRunE:       promptCurrentContext,
given that this affects basically every command in the book though, i dont want to fix this now, and would rather come up with a global solution separately

2021-06-15 00:09 UTC, jkminneti commented on cmd/deploy.go
> +	PreRunE:       promptCurrentContext,
to be clear i did leave it with ExactArgs for now

2021-06-15 03:41 UTC, quinn-freshly approved these changes

2021-06-15 03:55 UTC, merged