the final dan ism
Freshly/tuber pull request #231
Opened 2021-06-20 18:10 UTC by jkminneti

```go
viper.GetString("some-string") -> viper.GetString("TUBER_SOME_STRING")
```
what a destructive bit of "convenience"

2021-06-21 16:37 UTC, quinn-freshly requested changes

2021-06-21 16:37 UTC, quinn-freshly commented on main.go
> -	viper.SetDefault("prefix", "/tuber")
this is necessary

2021-06-21 16:39 UTC, quinn-freshly requested changes

2021-06-21 16:39 UTC, quinn-freshly commented on pkg/adminserver/server.go
> +	mux.Handle(prefixRoute("/graphql", s.prefix), graph.Handler(s.db, s.processor, s.logger, s.creds, s.triggersProjectName, s.clusterName, s.clusterRegion))
:(

2021-06-24 02:28 UTC, jkminneti commented on pkg/adminserver/server.go
> +	mux.Handle(prefixRoute("/graphql", s.prefix), graph.Handler(s.db, s.processor, s.logger, s.creds, s.triggersProjectName, s.clusterName, s.clusterRegion))
?

2021-06-25 22:59 UTC, quinn-freshly commented on pkg/adminserver/server.go
> +	mux.Handle(prefixRoute("/graphql", s.prefix), graph.Handler(s.db, s.processor, s.logger, s.creds, s.triggersProjectName, s.clusterName, s.clusterRegion))
@jkminneti it was so much cleaner before 😢

2021-06-25 23:41 UTC, jkminneti commented on pkg/adminserver/server.go
> +	mux.Handle(prefixRoute("/graphql", s.prefix), graph.Handler(s.db, s.processor, s.logger, s.creds, s.triggersProjectName, s.clusterName, s.clusterRegion))
@quinn-freshly i wanna keep viper (or indeed any env getting) out in the `cmd` package. `pkg` stuff should have explicit inputs imo

we have, afaik, kept that up in all cases but the debug mode check within kubectl.go

2021-06-26 00:17 UTC, quinn-freshly approved these changes

2021-06-26 02:19 UTC, merged