Expand dns1123 processing
Freshly/tuber pull request #250
Opened 2021-07-22 16:33 UTC by jaysonesmith

Tests show various formats that get processed as well as some standard success cases.

2021-07-22 16:51 UTC, quinn-freshly requested changes
this is great, thanks for adding test cases for this. a few changes i think would be nice, but you can disregard. 

Also, I wonder if it would be worth adding in the hyphen plus 4 or 5 random alphanum characters at the end inside this PR?

2021-07-22 16:51 UTC, quinn-freshly commented on pkg/reviewapps/reviewapps_test.go
> +			expected: strings.Repeat("a", dns1123NameMaximumLength),
maybe i'm old fashioned, but its nice to see the explicit value and the explicit output in tests. This doesn't make the test resilient to changes in the "max length" constant, but i prefer to see the failing test after the constant is changed, then updated to be green again.

2021-07-22 16:51 UTC, quinn-freshly commented on pkg/reviewapps/reviewapps_test.go
> +			expected: fmt.Sprintf("review-app-%d", time.Now().Unix()),
nice.

2021-07-22 16:51 UTC, quinn-freshly commented on pkg/reviewapps/reviewapps_test.go
> +			input:    "foo-",
can you add a double trailing hyphen here, or add a test case for more than one hyphen?

2021-07-22 16:54 UTC, jaysonesmith commented on pkg/reviewapps/reviewapps_test.go
> +			input:    "foo-",
Yea of course!

2021-07-22 16:54 UTC, jaysonesmith commented on pkg/reviewapps/reviewapps_test.go
> +			expected: fmt.Sprintf("review-app-%d", time.Now().Unix()),
🎉  Normally finding a way to inject a custom time object for testing but don't want to change the signature.

2021-07-22 16:56 UTC, jaysonesmith commented on pkg/reviewapps/reviewapps_test.go
> +			expected: strings.Repeat("a", dns1123NameMaximumLength),
Yea, totally fine.

2021-07-22 17:02 UTC, jaysonesmith commented on pkg/reviewapps/reviewapps_test.go
> +			expected: strings.Repeat("a", dns1123NameMaximumLength),
I'm updating the test case to have hard coded values with the input being > 63 characters as that's what the actual spec dictates. This'll mean we'll only need to change the expected value if we do end up changing the const value down the line.

2021-07-22 17:06 UTC, jaysonesmith commented
@quinn-freshly Good call on the leading hyphens as that actually wasn't handled. 🙏

2021-07-22 17:12 UTC, quinn-freshly approved these changes

2021-07-22 18:29 UTC, jkminneti approved these changes
point about style, otherwise lgtm

2021-07-22 18:29 UTC, jkminneti commented on pkg/reviewapps/reviewapps.go
> +		switch {
this seems a little unnecessarily complicated
```go
if dns1123LabelRe.Match(n) {
	return string(n)
}
n = bytes.ToLower(n)
n = bytes.ReplaceAll(n, []byte("_"), []byte("-"))
n = symbolsRe.ReplaceAll(n, []byte(""))
n = bytes.Trim(n, "-")
if !dns1123LabelRe.Match(n) {
	return fmt.Sprintf("review-app-%d", time.Now().Unix())
}
```
it's true, as-is, some of those transformations are skipped if unnecessary. but is that worth the extra and repetitive checks, if it's also arguably less readable?

def a style question tho

2021-08-29 20:57 UTC, Hbbb approved these changes
Let's merge this!

2021-09-08 22:48 UTC, jkminneti requested changes

2021-09-08 22:48 UTC, jkminneti commented on pkg/reviewapps/reviewapps.go
> +			return fmt.Sprintf("review-app-%d", time.Now().Unix())
turns out it has to end in an alpha character

2021-09-08 23:30 UTC, jkminneti approved these changes

2021-09-08 23:30 UTC, jkminneti commented on pkg/events/processor_test.go
> +package events
this supposed to be here?

2021-09-08 23:30 UTC, jkminneti commented on go.sum
> -cloud.google.com/go/bigquery v1.8.0 h1:PQcPefKFdaIzjQFbiyOgAqyx8q5djaE7x9Sqe712DPA=
wow i thought this was cus of outdated main, but nope main is untidied

2021-09-09 20:37 UTC, jaysonesmith commented on pkg/events/processor_test.go
> +package events
Nope

2021-09-09 22:31 UTC, merged