POPS-1149 Add build statuses to dashboard
Freshly/tuber pull request #251
Opened 2021-07-22 17:16 UTC by Hbbb

Adds Cloud Build statuses to the dashboard

<img width="769" alt="qa-replicated_-_staging" src="https://user-images.githubusercontent.com/3803272/126680911-5908ea17-0408-4859-af39-2c9af4014c1d.png">

2021-07-22 18:38 UTC, jkminneti requested changes

2021-07-22 18:38 UTC, jkminneti commented on graph/schema.resolvers.go
> +	builds, err := builds.FindByApp(obj, "freshly-docker")
needs to be passed in from the top

2021-07-23 17:14 UTC, Hbbb commented on graph/schema.resolvers.go
> +	builds, err := builds.FindByApp(obj, "freshly-docker")
Yep. I noticed that the resolver's `projectName` is actually the server's `triggersProjectName`. The `projectName` field on the server struct is redundant.

2021-07-23 20:59 UTC, jkminneti approved these changes

2021-07-23 21:02 UTC, merged