user impersonation
Freshly/tuber pull request #254
Opened 2021-08-04 13:54 UTC by jkminneti

env vars:

```
tuber env set TUBER_OAUTH_REDIRECT_URL "https://admin.freshlyhq.com/tuber/auth" -a tuber -y
tuber env set TUBER_OAUTH_WEB_CLIENT_SECRET {web client from ui for each project} -a tuber -y
tuber env set TUBER_OAUTH_WEB_CLIENT_ID {web client from ui for each project} -a tuber -y
tuber env set TUBER_OAUTH_STATE_KEY asdfasdf -a tuber -y
```

This is still an incomplete first step.

I couldn't (or wouldn't) get nextjs to follow server redirects (server sends 301 and a target, and nextjs is like "cool but like where's the data i asked for")

so you have to go to, in the deployed case of internal, `https://admin.freshlyhq.com/tuber/login` to get yourself a cookie or two

But beyond that (easily fixed once supported), this works.

The point of this PR is to offer to our graphql resolvers this function:
```
func GetAccessToken(ctx context.Context) (string, error) {}
```
any endpoint that needs a `kubectl auth can-i` or full user impersonation can rely on that return.

a proof of that is in the dashboard homepage - it does nothing with the output of the can-i, but the proof is in the logs.

2021-08-10 20:48 UTC, jaysonesmith commented on pkg/adminserver/server.go
> +		}
Same question here as on your other PR about -always- returning unauthed regardless of whether or not the `TrySetCookieAuthContext` errors

2021-08-10 20:49 UTC, jaysonesmith commented on pkg/adminserver/server.go
> +		http.Redirect(w, r, fmt.Sprintf("/tuber/unauthorized/&error=%s", "no auth code returned from iap"), http.StatusUnauthorized)
Do we need the sprintf here? A single string seems suitable

2021-08-10 20:55 UTC, jaysonesmith approved these changes

2021-08-29 20:29 UTC, Hbbb requested changes
I'd like to chat about some of the decisions around refreshing the auth stuff, but otherwise this looks good :)

2021-08-29 20:29 UTC, Hbbb commented on pkg/adminserver/server.go
> +			http.Redirect(w, r, fmt.Sprintf("/tuber/unauthorized/&error=%s", err.Error()), http.StatusInternalServerError)
If we fail to set the cookie here, why don't we just redirect them back to the `RefreshTokenConsentUrl` and have them try again?

2021-08-29 20:29 UTC, Hbbb commented on pkg/oauth/oauth.go
> +		encodedAccess, err := sc.Encode(refreshTokenCookieKey(), accessToken)
Did you mean to use `accessTokenCookieKey` here?

2021-08-29 20:29 UTC, Hbbb commented on pkg/adminserver/server.go
> +			http.Redirect(w, r, fmt.Sprintf("/tuber/unauthorized/&error=%s", err.Error()), http.StatusInternalServerError)
To expand on this further, `TrySetCookieAuthContext` has a ton of failure paths bubbling up from low level operations like decoding cookies etc.

If there are any issues decoding the cookies or with the result of refreshing a token, for example, maybe we should just remove the bad cookies and redirect the user to the consent screen again?

2021-08-29 20:29 UTC, Hbbb commented on pkg/oauth/oauth.go
> +type oauthCtxKey string
What's the purpose of this type? It doesn't seem like we're enforcing it anywhere.

2021-09-17 22:32 UTC, Hbbb approved these changes

2021-09-17 22:32 UTC, merged