multiple sentries per resource
Freshly/tuber pull request #256
Opened 2021-08-06 18:30 UTC by jkminneti

`tuber/sentryUrl` will work fine for backwards compatibility
add as many as you want with that prefix

2021-08-09 19:59 UTC, jaysonesmith requested changes
Just the one. :)

2021-08-09 19:59 UTC, jaysonesmith commented on pkg/core/releaser.go
> +				healthy, message := monitor.Sentry(logger, url, r.sentryBearerToken, resource.watchDuration)
[C2 - Potentially broken under certain circumstances](https://production.admin.freshlyservices.net/engineering-handbook/docs/processes/software-development/code-review/#c2---potentially-broken-under-certain-circumstances)

VS Code alerted me to the use of `url` here.

<img width="622" alt="Screen Shot 2021-08-09 at 12 50 46 PM" src="https://user-images.githubusercontent.com/21065409/128765738-de05b895-1e88-46a1-98b2-661712da986e.png">

I did a google and found [this](https://eli.thegreenplace.net/2019/go-internals-capturing-loop-variables-in-closures/) page which says that due to the way go's internals work, we'd only ever add the last url in `resource.sentryUrls` `len(resource.sentryUrls)` times.  AFAIK the fix would be to pass the url into the closure like below?

```go
			go func(errors chan rolloutError, wg *sync.WaitGroup, url string) {
				_, logger := resource.scopes(r)
				healthy, message := monitor.Sentry(logger, url, r.sentryBearerToken, resource.watchDuration)
				if !healthy {
					errors <- rolloutError{
						err:                fmt.Errorf("sentry monitoring found failure"),
						resource:           resource,
						monitorFail:        true,
						monitorFailMessage: message,
					}
				}
				wg.Done()
			}(errors, wg, url)
```

2021-08-09 20:22 UTC, jaysonesmith commented on pkg/core/releaser.go
> +				healthy, message := monitor.Sentry(logger, url, r.sentryBearerToken, resource.watchDuration)
I've verified this locally with a test function similar to the current implementation and got:

```go
urls := []string{"url-one", "url-two", "url-three"}

// out:
// i: 2, url: "url-three"
// i: 2, url: "url-three"
// i: 2, url: "url-three"
```

2021-08-09 20:38 UTC, jkminneti commented on pkg/core/releaser.go
> +				healthy, message := monitor.Sentry(logger, url, r.sentryBearerToken, resource.watchDuration)
YUUUUUP shoot nice catch

2021-08-09 20:40 UTC, jkminneti commented on pkg/core/releaser.go
> +				healthy, message := monitor.Sentry(logger, url, r.sentryBearerToken, resource.watchDuration)
in fact how did neither goland nor staticcheck catch that wtf

2021-08-23 17:56 UTC, jaysonesmith approved these changes

2021-08-23 22:51 UTC, merged